import type { InsertTestimonial } from "./schema";

type SeedTestimonial = Omit<InsertTestimonial, "location" | "image"> &
  Partial<Pick<InsertTestimonial, "location" | "image">>;

// Hand-curated 5-star reviews from the practice's Yelp page
// (https://www.yelp.com/biz/christopher-b-wong-dds-palo-alto).
// Transcribed from Yelp; the business-owner reply and Yelp UI metadata
// (friend/review/photo counts) are intentionally excluded, and one truncated
// review was trimmed to its last complete sentence. `location` carries the
// source label (mirrors the "Google Review" convention); it is not rendered.
export const yelpReviewSeedData: SeedTestimonial[] = [
  {"name":"Sue R.","rating":5,"location":"Yelp Review","text":"If only there were more than five stars to give Dr Wong and his team! I know from personal experience that Dr. Wong is a true master of dental science, and his cosmetic dental art is flawless! Helen is the most caring, kind, and meticulous of dental hygienists ever. She takes her time to explain everything with knowledge and clarity. I'm so grateful to be their patient and without any reservation thoroughly recommend this dental office. Written by me and not AI. :)"},
  {"name":"Helen T.","rating":5,"location":"Yelp Review","text":"Even though he's now out-of-network for us, we've chosen to stay. That says a lot. The reality is dental insurance hasn't kept up — reimbursement rates are practically stuck in the early 2000s — and many excellent dentists have had to make tough business decisions. I completely understand it. Quality care and experienced staff deserve fair compensation. Dr. Wong is thoughtful, thorough, and never rushes appointments. He explains things clearly and takes a conservative approach, which I truly appreciate. His hygienists are fantastic — gentle but meticulous — and you leave feeling like your teeth got the five-star treatment. The front desk team is consistently polite, organized, and efficient. Scheduling is smooth, billing is transparent, and they're always patient with questions. Great dentistry, great team, and well worth staying with — insurance or not."},
  {"name":"Brandi H.","rating":5,"location":"Yelp Review","text":"Angelise has been my dental hygienist for over 20 years, and I can't recommend her highly enough. She is truly passionate about patient care and always takes the time to provide exceptional service. I actually look forward to my dental cleanings because I know my teeth will feel amazing afterward. Her attention to detail, extensive experience, and gentle approach make every visit comfortable and thorough. On top of that, her warm and friendly personality makes you feel genuinely cared for. Angelise is a true professional and an outstanding hygienist. I feel very fortunate to have been her patient for so many years."},
  {"name":"Ang N.","rating":5,"location":"Yelp Review","text":"I always have an awesome experience at Dr. Wong's office. He's caring, professional, and makes everything easy to understand. You can tell he truly looks out for his patients. And Angelisa, my hygienist, is amazing! Cleanings with her are fun, gentle, and somehow fly by. I leave with sparkling teeth and in a great mood every single time. :)"},
  {"name":"Mark B.","rating":5,"location":"Yelp Review","text":"Christopher Wong DDS and his staff are the best! Excellent care, friendly and organized office, and Helen is the best dental hygienist I have ever had. I actually look forward to going to the dentist every 6 months!"},
  {"name":"Tirzah A.","rating":5,"location":"Yelp Review","text":"Everyone here is so kind and easy to work with. We've been coming here for dental care for decades and seen 2 generations of dentists into their retirement and subsequent turnovers. New and previous team members so far so good. Empathetic and detail oriented."},
  {"name":"Martha H.","rating":5,"location":"Yelp Review","text":"Dr. Wong is an incredibly skilled dentist & I like that he is conservative in his approach to work that may be needed. The staff is always friendly and welcoming. Kelty at the front desk is so sweet, and Rachel is extremely knowledgeable about my dental insurance coverage. Angelisa & Helen are the best hygienists."},
  {"name":"Elsie C.","rating":5,"location":"Yelp Review","text":"Dr. Wong, Helen, Amber and all the staff are professional, friendly and helpful! Thank you for taking care of the oral health of my family over the years."},
  {"name":"Steve L.","rating":5,"location":"Yelp Review","text":"Dr. Wong is fantastic. Shout out to our favorite hygienist, Helen! They are all very friendly and provide expert care."},
  {"name":"Elyse M.","rating":5,"location":"Yelp Review","text":"I found the doctor easy to talk to and they made sure I understood all the advice given. The support staff were efficient and the waiting time was reasonable. The doctor's approach was practical and patient focused which made me feel comfortable discussing my concerns."},
];
