import fs from "node:fs";
import path from "node:path";

type ParsedReview = {
  name: string;
  rating: number;
  date: string;
  text: string;
  location: string;
};

const inputArg = process.argv[2];
const inputPath = inputArg
  ? path.resolve(inputArg)
  : path.resolve("attached_assets/google-reviews-export-319.txt");
const outputPath = path.resolve("shared/googleReviewsData.ts");

function parseReviewBlock(block: string): ParsedReview | null {
  const reviewerMatch = block.match(/Reviewer:\s*(.+)/);
  const starsMatch = block.match(/Stars:\s*(\d+)\/5/);
  const dateMatch = block.match(/Date:\s*(.+)/);
  const reviewMatch = block.match(/Review:\s*([\s\S]*?)\s*$/);

  if (!reviewerMatch || !starsMatch || !dateMatch || !reviewMatch) {
    return null;
  }

  const name = reviewerMatch[1].trim();
  const rating = Number(starsMatch[1]);
  const date = dateMatch[1].trim();

  let text = reviewMatch[1]
    .replace(/\n+\s*---\s*$/g, "")
    .replace(/\s+/g, " ")
    .trim();

  if (text === "[No text]") {
    text = `Left a ${rating}-star Google review with no additional comment.`;
  }

  // Keep excerpt semantics while removing dump marker noise.
  text = text.replace(/\.\.\.\s*\[truncated\]/gi, "...");

  return {
    name,
    rating,
    date,
    text,
    location: "Google Review",
  };
}

function parseAllReviews(content: string): ParsedReview[] {
  const blocks = content
    .split(/\n-{3,}\n/g)
    .map((block) => block.trim())
    .filter((block) => block.includes("Review #"));

  const parsed: ParsedReview[] = [];
  for (const block of blocks) {
    const item = parseReviewBlock(block);
    if (!item) continue;
    parsed.push(item);
  }

  return parsed;
}

function formatTs(reviews: ParsedReview[]): string {
  const rows = reviews.map((review) => {
    const obj = {
      name: review.name,
      rating: review.rating,
      location: review.location,
      text: review.text,
    };
    return `  ${JSON.stringify(obj)},`;
  });

  return [
    "import type { InsertTestimonial } from \"./schema\";",
    "",
    "type SeedTestimonial = Omit<InsertTestimonial, \"location\" | \"image\"> &",
    "  Partial<Pick<InsertTestimonial, \"location\" | \"image\">>;",
    "",
    "// Generated by scripts/import-google-reviews.ts from Google review export text",
    "export const googleReviewSeedData: SeedTestimonial[] = [",
    ...rows,
    "];",
    "",
  ].join("\n");
}

function main() {
  if (!fs.existsSync(inputPath)) {
    throw new Error(`Input file not found: ${inputPath}`);
  }

  const content = fs.readFileSync(inputPath, "utf8");
  const reviews = parseAllReviews(content);

  if (reviews.length < 300) {
    throw new Error(
      `Parsed only ${reviews.length} reviews. Expected around 319. Check input formatting.`,
    );
  }

  const expectedCount = 319;
  if (reviews.length !== expectedCount) {
    console.warn(
      `Warning: parsed ${reviews.length} reviews (expected ${expectedCount}). Proceeding with parsed count.`,
    );
  }

  const seen = new Set<string>();
  const deduped: ParsedReview[] = [];
  for (const review of reviews) {
    const key = `${review.name}::${review.text}`;
    if (seen.has(key)) continue;
    seen.add(key);
    deduped.push(review);
  }

  fs.writeFileSync(outputPath, formatTs(deduped));
  console.log(`Wrote ${deduped.length} reviews to ${outputPath}`);
}

main();
